# Generated by Django 5.1.7 on 2025-05-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='books_cover',
            field=models.ImageField(blank=True, upload_to='books_cover'),
        ),
    ]
