# Generated by Django 5.1.7 on 2025-05-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_books_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='books_cover',
            field=models.ImageField(blank=True, upload_to='books_cover/'),
        ),
    ]
